### ISSUE TITLE
Doubt about Race Condition in Second Notebook

### ISSUE THREAD

**Issue by IamGroot19** [santiagobasulto/pycon-concurrency-tutorial-2020#10]
If Python has GIL (which prevents race condition & creates thread safety), then how come the multi-threaded program in notebook2 resulted in a wrong value of COUNTER? 

I am guessing the example was wrong because for me, I let the threads execute fully before running the `assert` statement. (Code below):

**Cell 1**
```import time, random, threading```

**Cell 2**
```
# Race Condition example (Part 1)
COUNTER = 0

# Race Condition example (Part 2)
def increement(n):
    global COUNTER # Use the global variable declared above
    for _ in range(n):
        COUNTER += 1
        time.sleep(0.001)
    print( f"\n{threading.current_thread().name} finished counting")

ITERATIONS = 100000 # set no of iterations to increase counter

# create 10 threads each set to run the increement() function for 1k iteations
threads = [threading.Thread(target=increement, args=(ITERATIONS,) )\
               for _ in range(10) ]

print(COUNTER)
```

**Cell 3**
```
[ t.start() for t in threads] # start computation
[ t.join() for t in threads ]
```

**Cell4**
```
print('\nCounter: ', COUNTER, '\n')
assert COUNTER == (len(threads) * ITERATIONS),\
 f"Invalid value for counter: {COUNTER}, expected value: {len(threads) * ITERATIONS}"
 ```

I guess a better example to demonstrtate race condition would be something like the following since in this case updation of the `COUNTER` is no longer atomic.  (Kindly let me know if this makes sense so that I can apply for a Pull request). 
```
def increement(n):
    global COUNTER # Use the global variable declared above
    for _ in range(n):
        x =  COUNTER
        COUNTER = x + 1
        time.sleep(0.001)
    print( f"\n{threading.current_thread().name} finished counting")

**Comment by zzhengnan** [comment]
Despite its appearance as a one-liner, `COUNTER += 1` actually consists of multiple bytecode instructions, which you can inspect using the [dis](https://docs.python.org/3/library/dis.html) module from the standard library. 

As seen below, 3 distinct bytecode instructions are actually needed to carry out `COUNTER += 1`.

```python
>>> counter = 0
>>> def inc_global_counter():
...     global counter
...     counter += 1

>>> import dis
>>> dis.dis(inc_global_counter)
  3           0 LOAD_GLOBAL              0 (counter)  # 1. Load global variable `counter`
              2 LOAD_CONST               1 (1)        
              4 INPLACE_ADD                           # 2. Increment by one
              6 STORE_GLOBAL             0 (counter)  # 3. Update global variable with new value
              8 LOAD_CONST               0 (None)
             10 RETURN_VALUE
```

The GIL doesn't help prevent the kind of race conditions presented in the notebook. Specifically, if multiple threads are running the `increment` function, it's possible for a thread to get interrupted _right before_ the `STORE_GLOBAL` bytecode is executed (which updates the counter value). Accumulated over thousands of iterations, this will result in a final counter value that's less than the expected number.

I highly recommend the following post. It's got a nice visual that explains this exact race condition.
https://realpython.com/intro-to-python-threading/#two-threads

**Comment by santiagobasulto** [comment]
This is a great explanation @zzhengnan, thanks for helping out.
